version: "2"

services:
  slim:
    build: ./slim-image
    volumes:
      - ./slim-app:/var/www/html
      - ./logs:/var/log/apache2
    ports:
      - "9001:80"
    depends_on:
      - db
    environment:
      APPLICATION_ENV: local    
      XDEBUG_CONFIG: remote_host=172.25.166.81

  db:
    image: mysql:5.6
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=slim
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=slim_db
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions